export const mockArticles = [
  {
    id: '1',
    title: 'New Study Links Mediterranean Diet to Reduced Alzheimer\'s Risk',
    content: 'A comprehensive 10-year study involving 15,000 participants has found that adherence to a Mediterranean diet rich in olive oil, fish, and vegetables may reduce the risk of developing Alzheimer\'s disease by up to 40%. Researchers at Johns Hopkins University discovered that the anti-inflammatory properties of omega-3 fatty acids and polyphenols play a crucial role in protecting brain cells from oxidative stress. The study also highlighted the importance of consistent dietary patterns over sporadic healthy eating. Participants who maintained the diet for at least 5 years showed the most significant cognitive benefits.',
    source: 'Medical News Today',
    publishedAt: '2024-09-28T10:30:00Z',
    url: 'https://example.com/article1',
  },
  {
    id: '2',
    title: 'Exercise Found to Be as Effective as Medication for Depression',
    content: 'A groundbreaking meta-analysis published in the British Medical Journal reviewed 150 clinical trials and concluded that regular physical activity can be as effective as antidepressant medications for treating mild to moderate depression. The research team found that 30 minutes of moderate exercise five times per week led to significant improvements in mood, sleep quality, and overall mental health. Cardiovascular exercises like jogging, swimming, and cycling showed the strongest effects, though resistance training also provided substantial benefits.',
    source: 'Harvard Health',
    publishedAt: '2024-09-27T14:20:00Z',
    url: 'https://example.com/article2',
  },
  {
    id: '3',
    title: 'Sleep Deprivation Increases Risk of Heart Disease by 48%',
    content: 'Recent cardiovascular research from the American Heart Association reveals that individuals who consistently sleep less than 6 hours per night face a 48% increased risk of developing heart disease compared to those getting 7-8 hours. The study tracked 50,000 adults over 20 years and found that chronic sleep deprivation triggers inflammatory responses, elevated blood pressure, and disrupted glucose metabolism. Researchers noted that even one week of inadequate sleep can lead to measurable changes in heart function.',
    source: 'WebMD',
    publishedAt: '2024-09-26T09:15:00Z',
    url: 'https://example.com/article3',
  },
  {
    id: '4',
    title: 'Gut Microbiome Diversity Linked to Longevity in Centenarians',
    content: 'Scientists studying centenarians across five continents have discovered that exceptional longevity is strongly associated with remarkable diversity in gut bacteria. The research identified specific bacterial strains that produce compounds capable of reducing inflammation and supporting immune function. Participants over 100 years old showed microbiome compositions significantly different from younger adults, with higher levels of beneficial bacteria like Akkermansia and Bifidobacterium.',
    source: 'Nature Medicine',
    publishedAt: '2024-09-25T11:45:00Z',
    url: 'https://example.com/article4',
  },
  {
    id: '5',
    title: 'Intermittent Fasting Shows Promise in Managing Type 2 Diabetes',
    content: 'A clinical trial conducted at the University of California examined 300 adults with Type 2 diabetes who practiced time-restricted eating for 12 months. Results showed that 60% of participants achieved significant improvements in blood glucose control, with average HbA1c levels dropping by 1.5 points. The 16:8 fasting protocol (16 hours fasting, 8 hours eating window) proved most effective and sustainable for participants. Researchers observed enhanced insulin sensitivity and reduced medication requirements in many cases.',
    source: 'Diabetes Care Journal',
    publishedAt: '2024-09-24T13:30:00Z',
    url: 'https://example.com/article5',
  },
  {
    id: '6',
    title: 'Screen Time Before Bed Disrupts Children\'s Sleep Patterns',
    content: 'Pediatric sleep researchers have found that children exposed to screens within two hours of bedtime experience significant disruptions in sleep quality and duration. The study involving 5,000 children aged 6-14 revealed that blue light exposure suppresses melatonin production by up to 55%, delaying sleep onset by an average of 45 minutes. Children who avoided evening screen time fell asleep faster and reported feeling more rested upon waking.',
    source: 'Pediatrics Journal',
    publishedAt: '2024-09-23T08:00:00Z',
    url: 'https://example.com/article6',
  },
  {
    id: '7',
    title: 'Vitamin D Deficiency Affects Nearly 50% of Global Population',
    content: 'A comprehensive global health survey published in The Lancet estimates that approximately 50% of the world\'s population has insufficient vitamin D levels, with serious implications for bone health, immune function, and mental well-being. The research identified limited sun exposure, geographic location, and dietary habits as primary contributing factors. Vitamin D deficiency has been linked to increased susceptibility to respiratory infections, autoimmune disorders, and mood disturbances.',
    source: 'The Lancet',
    publishedAt: '2024-09-22T10:20:00Z',
    url: 'https://example.com/article7',
  },
  {
    id: '8',
    title: 'Mindfulness Meditation Reduces Chronic Pain by 30%',
    content: 'Neuroscientists at Stanford University have demonstrated that regular mindfulness meditation can reduce chronic pain intensity by an average of 30% without medication. Brain imaging studies showed that meditation alters pain perception by modifying activity in brain regions associated with emotional regulation and sensory processing. Participants who practiced 20 minutes of daily meditation for 8 weeks reported improved quality of life and reduced reliance on pain medications.',
    source: 'Pain Medicine Journal',
    publishedAt: '2024-09-21T15:10:00Z',
    url: 'https://example.com/article8',
  },
  {
    id: '9',
    title: 'Plant-Based Proteins Reduce Cardiovascular Disease Risk',
    content: 'Nutritional epidemiologists analyzing data from 400,000 individuals found that replacing animal proteins with plant-based alternatives reduces cardiovascular disease risk by 25%. The study highlighted that legumes, nuts, seeds, and whole grains provide protective benefits through their fiber content, antioxidants, and healthy fatty acid profiles. Participants who consumed at least 50% of their protein from plant sources showed lower cholesterol levels, reduced blood pressure, and healthier body weights.',
    source: 'Circulation Journal',
    publishedAt: '2024-09-20T12:40:00Z',
    url: 'https://example.com/article9',
  },
  {
    id: '10',
    title: 'Social Connection as Important as Exercise for Longevity',
    content: 'A landmark longitudinal study spanning 80 years has concluded that strong social relationships are as crucial to longevity as regular exercise and a healthy diet. Researchers at Harvard found that individuals with robust social networks lived longer, experienced less cognitive decline, and reported higher life satisfaction. The quality of relationships proved more important than quantity, with close, supportive connections providing the greatest health benefits.',
    source: 'Harvard Medical School',
    publishedAt: '2024-09-19T09:30:00Z',
    url: 'https://example.com/article10',
  },
  {
    id: '11',
    title: 'Air Pollution Linked to Increased Autism Risk in Children',
    content: 'Environmental health researchers have identified a correlation between prenatal exposure to air pollution and increased autism spectrum disorder (ASD) diagnosis rates. The study examined 100,000 births and found that mothers living in areas with high particulate matter concentrations during pregnancy had a 20% higher likelihood of having children diagnosed with ASD. Fine particulate matter (PM2.5) appears to cross the placental barrier and affect fetal brain development.',
    source: 'Environmental Health Perspectives',
    publishedAt: '2024-09-18T14:50:00Z',
    url: 'https://example.com/article11',
  },
  {
    id: '12',
    title: 'Hydration Status Affects Cognitive Performance Significantly',
    content: 'Cognitive neuroscience research demonstrates that even mild dehydration of 2% body water loss impairs memory, attention, and decision-making abilities. The study involving 500 participants found that dehydrated individuals performed 15-20% worse on cognitive tests compared to their hydrated baseline. Brain imaging revealed that dehydration affects neural efficiency and increases the effort required for mental tasks.',
    source: 'Journal of Nutrition',
    publishedAt: '2024-09-17T11:15:00Z',
    url: 'https://example.com/article12',
  },
];